-- =====================================================================
-- Tienda Emprendedores Regionales - Esquema para PostgreSQL
-- =====================================================================
-- Migrado desde el script de SQL Server (database/TiendaEmprendedoresRegionales.sql).
--
-- Cómo correrlo:
--   psql "<DATABASE_URL>" -f database/postgres/01_esquema.sql
--   (o pegarlo en el SQL Editor de Neon)
--
-- IMPORTANTE - nombres con mayúsculas o ñ:
--   PostgreSQL pasa a minúsculas todo nombre que no esté entre comillas dobles.
--   Para que la API siga devolviendo los mismos nombres que antes
--   (DNI, nombreEmprendimiento, id_itemCarrito, etc.), esas columnas están
--   creadas entre comillas y HAY QUE ESCRIBIRLAS ENTRE COMILLAS en cada consulta:
--       SELECT "DNI", "nombreEmprendimiento" FROM Usuario      -- bien
--       SELECT DNI, nombreEmprendimiento FROM Usuario          -- error: no existe la columna
--   Las columnas en minúscula (id_producto, nombre, stock...) y los nombres de
--   tabla se escriben normal, sin comillas.
--
-- Cambios respecto de SQL Server:
--   IDENTITY(1,1)  -> GENERATED BY DEFAULT AS IDENTITY
--   FLOAT          -> DOUBLE PRECISION
--   DATETIME       -> TIMESTAMPTZ (guarda el instante exacto, con zona horaria)
--   VARCHAR(MAX)   -> TEXT
--   Valoración     -> Valoracion (tabla sin tilde)
--   Mensaje_Reclamo.imagen: el backend la usa pero faltaba en el script anterior.
--   Producto.imagen: ahora acepta NULL (el formulario permite crear sin imagen).
--   Los procedimientos sp_obtenerProductos y sp_actualizarProducto pasaron a ser
--   consultas dentro de backend/src/services/productoService.js.
-- =====================================================================


-- =============================================
-- 1. TABLAS MAESTRAS Y CONFIGURACIONES
-- =============================================

CREATE TABLE Rol (
  id_rol INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_Rol PRIMARY KEY (id_rol),
  CONSTRAINT UQ_Rol_Descripcion UNIQUE (descripcion)
);

INSERT INTO Rol (descripcion)
VALUES ('Administrador'), ('Emprendedor');


CREATE TABLE Estado (
  id_estado INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_Estado PRIMARY KEY (id_estado),
  CONSTRAINT UQ_Estado_Descripcion UNIQUE (descripcion),
  CONSTRAINT CK_Estado CHECK (descripcion IN ('Activo', 'Inactivo'))
);

INSERT INTO Estado (descripcion)
VALUES ('Activo'), ('Inactivo');


CREATE TABLE FormaPago (
  "id_formaPago" INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_FormaPago PRIMARY KEY ("id_formaPago"),
  CONSTRAINT UQ_FormaPago_Descripcion UNIQUE (descripcion)
);

INSERT INTO FormaPago (descripcion)
VALUES ('Efectivo'), ('Transferencia'), ('Tarjeta');


CREATE TABLE Categoria (
  id_categoria INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(200) NOT NULL,
  CONSTRAINT PK_Categoria PRIMARY KEY (id_categoria)
);

INSERT INTO Categoria (descripcion)
VALUES ('Artesanías'), ('Accesorios'), ('Gastronomía'), ('Textiles'), ('Decoración');


CREATE TABLE EstadoPago (
  "id_estadoPago" INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(200) NOT NULL,
  CONSTRAINT PK_EstadoPago PRIMARY KEY ("id_estadoPago"),
  CONSTRAINT UQ_EstadoPago_Descripcion UNIQUE (descripcion),
  CONSTRAINT CK_EstadoPago CHECK (descripcion IN ('Pendiente', 'Aprobado', 'Rechazado', 'Reembolsado'))
);

INSERT INTO EstadoPago (descripcion)
VALUES ('Pendiente'), ('Aprobado'), ('Rechazado'), ('Reembolsado');


CREATE TABLE estado_envio (
  id_estado_envio INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_EstadoEnvio PRIMARY KEY (id_estado_envio),
  CONSTRAINT UQ_EstadoEnvio_Descripcion UNIQUE (descripcion),
  CONSTRAINT CK_EstadoEnvio CHECK (descripcion IN ('En Preparacion', 'En Camino', 'Entregado', 'Cancelado'))
);

INSERT INTO estado_envio (descripcion)
VALUES ('En Preparacion'), ('En Camino'), ('Entregado'), ('Cancelado');


CREATE TABLE Estado_Reclamo (
  "id_estadoReclamo" INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_EstadoReclamo PRIMARY KEY ("id_estadoReclamo"),
  CONSTRAINT UQ_EstadoReclamo_Descripcion UNIQUE (descripcion),
  CONSTRAINT CK_EstadoReclamo CHECK (descripcion IN ('Pendiente', 'Respondido', 'Resuelto'))
);

INSERT INTO Estado_Reclamo (descripcion)
VALUES ('Pendiente'), ('Respondido'), ('Resuelto');


CREATE TABLE Estado_Producto (
  id_estado_prod INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_EstadoProducto PRIMARY KEY (id_estado_prod),
  CONSTRAINT UQ_EstadoProd_Descripcion UNIQUE (descripcion),
  CONSTRAINT CK_EstadoProducto CHECK (descripcion IN ('Con Stock', 'Sin Stock', 'Descontinuado'))
);

INSERT INTO Estado_Producto (descripcion)
VALUES ('Con Stock'), ('Sin Stock'), ('Descontinuado');


CREATE TABLE Estado_pedido (
  "id_estadoPedido" INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_EstadoPedido PRIMARY KEY ("id_estadoPedido"),
  CONSTRAINT UQ_EstadoPedido_Descripcion UNIQUE (descripcion),
  CONSTRAINT CK_EstadoPedido CHECK (descripcion IN ('Pendiente de Pago', 'Pagado', 'Cancelado'))
);

INSERT INTO Estado_pedido (descripcion)
VALUES ('Pendiente de Pago'), ('Pagado'), ('Cancelado');


CREATE TABLE Provincia (
  id_provincia INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  CONSTRAINT PK_Provincia PRIMARY KEY (id_provincia)
);


CREATE TABLE Tipo_envio (
  id_tipo_envio INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  costo_base DOUBLE PRECISION NOT NULL,
  CONSTRAINT PK_TipoEnvio PRIMARY KEY (id_tipo_envio),
  CONSTRAINT UQ_TipoEnvio_Descripcion UNIQUE (descripcion)
);


-- =============================================
-- 2. ENTIDADES PRINCIPALES Y LOCALIZACIÓN
-- =============================================

CREATE TABLE Cliente (
  id_cliente INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  "DNI" INT NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  email VARCHAR(50) NOT NULL,
  "contraseña" VARCHAR(255) NOT NULL,
  CONSTRAINT PK_Cliente PRIMARY KEY (id_cliente),
  CONSTRAINT UQ_Cliente_DNI UNIQUE ("DNI"),
  CONSTRAINT CK_Cliente_DNI CHECK ("DNI" BETWEEN 10000000 AND 99999999)
);

-- En SQL Server el email no distinguía mayúsculas de minúsculas.
-- Este índice mantiene esa regla: no puede haber Ana@mail.com y ana@mail.com.
CREATE UNIQUE INDEX UQ_Cliente_Email ON Cliente (LOWER(email));


CREATE TABLE Usuario (
  id_usuario INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  "DNI" INT NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  email VARCHAR(50) NOT NULL,
  "contraseña" VARCHAR(255) NOT NULL,
  "reseña" VARCHAR(255) NULL,
  "nombreEmprendimiento" VARCHAR(50) NULL,
  id_estado INT NOT NULL,
  id_rol INT NOT NULL,
  fecha_ultima_conexion TIMESTAMPTZ NULL,
  CONSTRAINT PK_Usuario PRIMARY KEY (id_usuario),
  CONSTRAINT FK_Usuario_Estado FOREIGN KEY (id_estado) REFERENCES Estado(id_estado),
  CONSTRAINT FK_Usuario_Rol FOREIGN KEY (id_rol) REFERENCES Rol(id_rol),
  CONSTRAINT UQ_Usuario_DNI UNIQUE ("DNI"),
  CONSTRAINT CK_Usuario_DNI CHECK ("DNI" BETWEEN 10000000 AND 99999999)
);

CREATE UNIQUE INDEX UQ_Usuario_Email ON Usuario (LOWER(email));

-- Usuario administrador inicial (admin@tienda.com).
-- El hash es el mismo que tenía el script de SQL Server. OJO: no corresponde a
-- "password123" (se probó con bcrypt). Si no recuerdan la contraseña original,
-- hay que generar un hash nuevo y actualizar esta fila.
INSERT INTO Usuario (
    nombre, apellido, "DNI", fecha_nacimiento, email, "contraseña",
    "reseña", "nombreEmprendimiento", id_estado, id_rol, fecha_ultima_conexion
)
VALUES (
    'Administrador', 'General', 12345678, '1990-01-01', 'admin@tienda.com',
    '$2b$10$Dgxwji.1PHDk3GEKGR/Ef0OC2V9mJ5jpxbcVvpJwqNLHMXcAHCu4e',
    NULL, NULL, 1, 1, NOW()
);


CREATE TABLE Ciudad (
  id_ciudad INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  cod_postal INT NOT NULL,
  id_provincia INT NOT NULL,
  CONSTRAINT PK_Ciudad PRIMARY KEY (id_ciudad),
  CONSTRAINT FK_Ciudad_Provincia FOREIGN KEY (id_provincia) REFERENCES Provincia(id_provincia)
);


-- =============================================
-- 3. TABLAS OPERATIVAS Y TRANSACCIONALES
-- =============================================

CREATE TABLE Direccion (
  id_direccion INT GENERATED BY DEFAULT AS IDENTITY,
  calle VARCHAR(50) NOT NULL,
  nro INT NOT NULL,
  descripcion VARCHAR(255) NULL,
  id_ciudad INT NOT NULL,
  CONSTRAINT PK_Direccion PRIMARY KEY (id_direccion),
  CONSTRAINT FK_Direccion_Ciudad FOREIGN KEY (id_ciudad) REFERENCES Ciudad(id_ciudad)
);


CREATE TABLE Producto (
  id_producto INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(200) NOT NULL,
  descripcion TEXT NOT NULL,
  stock INT NOT NULL,
  precio DOUBLE PRECISION NOT NULL,
  imagen TEXT NULL,
  id_categoria INT NOT NULL,
  id_estado_prod INT NOT NULL,
  id_usuario INT NOT NULL,
  CONSTRAINT PK_Producto PRIMARY KEY (id_producto),
  CONSTRAINT FK_Producto_Categoria FOREIGN KEY (id_categoria) REFERENCES Categoria(id_categoria),
  CONSTRAINT FK_Producto_Estado FOREIGN KEY (id_estado_prod) REFERENCES Estado_Producto(id_estado_prod),
  CONSTRAINT FK_Producto_Usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario),
  CONSTRAINT CK_Producto_Stock CHECK (stock >= 0),
  CONSTRAINT CK_Producto_Precio CHECK (precio > 0)
);


CREATE TABLE Carrito (
  id_carrito INT GENERATED BY DEFAULT AS IDENTITY,
  fecha_creacion TIMESTAMPTZ NOT NULL,
  "subTotal" DOUBLE PRECISION NOT NULL,
  id_cliente INT NOT NULL,
  CONSTRAINT PK_Carrito PRIMARY KEY (id_carrito),
  CONSTRAINT FK_Carrito_Cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente)
);


CREATE TABLE ItemCarrito (
  "id_itemCarrito" INT GENERATED BY DEFAULT AS IDENTITY,
  cantidad INT NOT NULL,
  precio DOUBLE PRECISION NOT NULL,
  id_producto INT NOT NULL,
  id_carrito INT NOT NULL,
  CONSTRAINT PK_ItemCarrito PRIMARY KEY ("id_itemCarrito"),
  CONSTRAINT FK_ItemCarrito_Producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto),
  CONSTRAINT FK_ItemCarrito_Carrito FOREIGN KEY (id_carrito) REFERENCES Carrito(id_carrito),
  CONSTRAINT UQ_ItemCarrito_Relacion UNIQUE (id_producto, id_carrito)
);


CREATE TABLE Envio (
  id_envio INT GENERATED BY DEFAULT AS IDENTITY,
  fecha_envio TIMESTAMPTZ NOT NULL,
  fecha_entrega TIMESTAMPTZ NULL,
  id_estado_envio INT NOT NULL,
  id_tipo_envio INT NOT NULL,
  CONSTRAINT PK_Envio PRIMARY KEY (id_envio),
  CONSTRAINT FK_Envio_Estado FOREIGN KEY (id_estado_envio) REFERENCES estado_envio(id_estado_envio),
  CONSTRAINT FK_Envio_Tipo FOREIGN KEY (id_tipo_envio) REFERENCES Tipo_envio(id_tipo_envio)
);


CREATE TABLE Pedido (
  id_pedido INT GENERATED BY DEFAULT AS IDENTITY,
  fecha_pedido TIMESTAMPTZ NOT NULL,
  "id_estadoPedido" INT NOT NULL,
  id_envio INT NOT NULL,
  id_cliente INT NOT NULL,
  id_direccion INT NOT NULL,
  CONSTRAINT PK_Pedido PRIMARY KEY (id_pedido),
  CONSTRAINT FK_Pedido_Estado FOREIGN KEY ("id_estadoPedido") REFERENCES Estado_pedido("id_estadoPedido"),
  CONSTRAINT FK_Pedido_Envio FOREIGN KEY (id_envio) REFERENCES Envio(id_envio),
  CONSTRAINT FK_Pedido_Cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente),
  CONSTRAINT FK_Pedido_Direccion FOREIGN KEY (id_direccion) REFERENCES Direccion(id_direccion)
);


CREATE TABLE Factura (
  id_factura INT GENERATED BY DEFAULT AS IDENTITY,
  fecha TIMESTAMPTZ NOT NULL,
  total DOUBLE PRECISION NOT NULL,
  id_pedido INT NOT NULL,
  CONSTRAINT PK_Factura PRIMARY KEY (id_factura),
  CONSTRAINT FK_Factura_Pedido FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido)
);


CREATE TABLE DetalleFactura (
  "id_detalleFactura" INT GENERATED BY DEFAULT AS IDENTITY,
  cantidad INT NOT NULL,
  precio_unitario DOUBLE PRECISION NOT NULL,
  id_factura INT NOT NULL,
  id_producto INT NOT NULL,
  id_carrito INT NOT NULL,
  CONSTRAINT PK_DetalleFactura PRIMARY KEY ("id_detalleFactura"),
  CONSTRAINT FK_DetalleFactura_Factura FOREIGN KEY (id_factura) REFERENCES Factura(id_factura),
  CONSTRAINT FK_DetalleFactura_Producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto),
  CONSTRAINT FK_DetalleFactura_Carrito FOREIGN KEY (id_carrito) REFERENCES Carrito(id_carrito)
);


CREATE TABLE Pago (
  id_pago INT GENERATED BY DEFAULT AS IDENTITY,
  fecha TIMESTAMPTZ NOT NULL,
  "montoTotal" DOUBLE PRECISION NOT NULL,
  id_factura INT NOT NULL,
  "id_formaPago" INT NOT NULL,
  "id_estadoPago" INT NOT NULL,
  CONSTRAINT PK_Pago PRIMARY KEY (id_pago),
  CONSTRAINT FK_Pago_Factura FOREIGN KEY (id_factura) REFERENCES Factura(id_factura),
  CONSTRAINT FK_Pago_Forma FOREIGN KEY ("id_formaPago") REFERENCES FormaPago("id_formaPago"),
  CONSTRAINT FK_Pago_Estado FOREIGN KEY ("id_estadoPago") REFERENCES EstadoPago("id_estadoPago")
);


-- =============================================
-- 4. SOPORTE Y CALIFICACIÓN
-- =============================================

CREATE TABLE Reclamo (
  id_reclamo INT GENERATED BY DEFAULT AS IDENTITY,
  fecha_reclamo TIMESTAMPTZ NOT NULL,
  motivo VARCHAR(255) NOT NULL,
  "id_estadoReclamo" INT NOT NULL,
  id_factura INT NOT NULL,
  id_cliente INT NOT NULL,
  CONSTRAINT PK_Reclamo PRIMARY KEY (id_reclamo),
  CONSTRAINT FK_Reclamo_Estado FOREIGN KEY ("id_estadoReclamo") REFERENCES Estado_Reclamo("id_estadoReclamo"),
  CONSTRAINT FK_Reclamo_Factura FOREIGN KEY (id_factura) REFERENCES Factura(id_factura),
  CONSTRAINT FK_Reclamo_Cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente)
);


CREATE TABLE Mensaje_Reclamo (
  id_mensaje INT GENERATED BY DEFAULT AS IDENTITY,
  contenido VARCHAR(255) NOT NULL,
  fecha_emision_mensaje TIMESTAMPTZ NOT NULL,
  id_reclamo INT NOT NULL,
  id_usuario INT NULL,      -- NULL = mensaje del cliente; con valor = mensaje del emprendedor
  imagen VARCHAR(255) NULL,
  CONSTRAINT PK_MensajeReclamo PRIMARY KEY (id_mensaje),
  CONSTRAINT FK_MensajeReclamo_Reclamo FOREIGN KEY (id_reclamo) REFERENCES Reclamo(id_reclamo)
);


CREATE TABLE Valoracion (
  id_valoracion INT GENERATED BY DEFAULT AS IDENTITY,
  puntaje INT NOT NULL,
  comentario VARCHAR(255) NULL,
  fecha TIMESTAMPTZ NOT NULL,
  id_cliente INT NOT NULL,
  id_factura INT NOT NULL,
  id_producto INT NOT NULL,
  CONSTRAINT PK_Valoracion PRIMARY KEY (id_valoracion),
  CONSTRAINT FK_Valoracion_Cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente),
  CONSTRAINT FK_Valoracion_Factura FOREIGN KEY (id_factura) REFERENCES Factura(id_factura),
  CONSTRAINT FK_Valoracion_Producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto),
  CONSTRAINT CK_Puntaje CHECK (puntaje BETWEEN 1 AND 5)
);


-- =============================================
-- 5. TRIGGER: ACTUALIZACIÓN DE STOCK Y ESTADO
-- =============================================
-- Cuando se registra un Pago 'Aprobado':
--   1) descuenta del stock las cantidades de la factura pagada
--   2) pasa a 'Sin Stock' los productos que quedaron en 0
-- En PostgreSQL un trigger son dos piezas: la función y el trigger que la llama.

CREATE OR REPLACE FUNCTION fn_actualizar_stock_y_estado()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM EstadoPago ep
    WHERE ep."id_estadoPago" = NEW."id_estadoPago"
      AND ep.descripcion = 'Aprobado'
  ) THEN
    UPDATE Producto p
    SET stock = p.stock - df.cantidad
    FROM DetalleFactura df
    WHERE df.id_producto = p.id_producto
      AND df.id_factura = NEW.id_factura;

    UPDATE Producto
    SET id_estado_prod = (
      SELECT id_estado_prod
      FROM Estado_Producto
      WHERE descripcion = 'Sin Stock'
    )
    WHERE stock = 0;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_ActualizarStockYEstado
AFTER INSERT ON Pago
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_stock_y_estado();
